function t121_setHeight(recid){var rec=$('#rec'+recid);var div=$("#youtubeiframe"+recid);var height=div.width()*0.5625;div.height(height);div.parent().height(height);var videoLazy=rec.find('.t-video-lazyload');var iframeLazy=videoLazy.find('iframe');if(videoLazy!=undefined){var heightLazy=videoLazy.width()*0.5625;videoLazy.height(heightLazy);iframeLazy.height(heightLazy)}}
function t452_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t453_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t453__item a[href='"+url+"']").addClass("t-active");$(".t453__item a[href='"+url+"/']").addClass("t-active");$(".t453__item a[href='"+pathname+"']").addClass("t-active");$(".t453__item a[href='/"+pathname+"']").addClass("t-active");$(".t453__item a[href='"+pathname+"/']").addClass("t-active");$(".t453__item a[href='/"+pathname+"/']").addClass("t-active")}
function t453_checkAnchorLinks(recid){if($(window).width()>=960){var t453_navLinks=$("#rec"+recid+" .t453__item a:not(.tooltipstered)[href*='#']");if(t453_navLinks.length>0){t453_catchScroll(t453_navLinks)}}}
function t453_catchScroll(t453_navLinks){var t453_clickedSectionId=null,t453_sections=new Array(),t453_sectionIdTonavigationLink={},t453_interval=100,t453_lastCall,t453_timeoutId,t453_offsetTop=$(".t453").attr("data-offset-top");if(typeof t453_offsetTop=="undefined"){t453_offsetTop=0}
t453_navLinks.each(function(){var t453_cursection=t453_getSectionByHref($(this));if(typeof t453_cursection.attr("id")!="undefined"){t453_sections.push(t453_cursection)}
t453_sectionIdTonavigationLink[t453_cursection.attr("id")]=$(this)});t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop);t453_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t453_navLinks.removeClass('t-active');t453_sectionIdTonavigationLink[t453_getSectionByHref($(this)).attr("id")].addClass('t-active');t453_clickedSectionId=t453_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t453_now=new Date().getTime();if(t453_lastCall&&t453_now<(t453_lastCall+t453_interval)){clearTimeout(t453_timeoutId);t453_timeoutId=setTimeout(function(){t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)},t453_interval-(t453_now-t453_lastCall))}else{t453_lastCall=t453_now;t453_clickedSectionId=t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,t453_offsetTop)}})}
function t453_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t453_highlightNavLinks(t453_navLinks,t453_sections,t453_sectionIdTonavigationLink,t453_clickedSectionId,offsetTop){var t453_scrollPosition=$(window).scrollTop(),t453_valueToReturn=t453_clickedSectionId;$(t453_sections).each(function(e){var t453_curSection=$(this),t453_sectionTop=t453_curSection.offset().top,t453_id=t453_curSection.attr('id'),t453_navLink=t453_sectionIdTonavigationLink[t453_id];if(t453_scrollPosition>=(t453_sectionTop-offsetTop)||(t453_sections[0].attr("id")==t453_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t453_clickedSectionId==null&&!t453_navLink.hasClass('t-active')){t453_navLinks.removeClass('t-active');t453_navLink.addClass('t-active');t453_valueToReturn=null}else{if(t453_clickedSectionId!=null&&t453_id==t453_clickedSectionId){t453_valueToReturn=null}}
return!1}});return t453_valueToReturn}
function t453_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t453").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");console.log(appearoffset)
if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t453__beforeready')){el.removeClass('t453__beforeready')}}else{el.addClass('t453__beforeready')}}})}
function t576_init(recid){var el=$('#rec'+recid),line=el.find('.t576__line'),cirqle=el.find('.t576__cicqle'),block=el.find('.t576__item'),t576_resize;block.each(function(){$(this).find('.t576__circle').css('top',$(this).find('.t576__img').outerHeight()+15)});el.find('.t576__item:first-child').find('.t576__line').css('top',el.find('.t576__item:first-child').find('.t576__img').outerHeight()+15);el.find('.t576__item:last-child').find('.t576__line').css('height',el.find('.t576__item:last-child').find('.t576__img').outerHeight()+20)}
function t796_init(recid){var el=$("#rec"+recid);var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){var curRec=el.next(".r");if(curRec.attr("data-record-type")=="215"||curRec.attr("data-record-type")=="706"){curRec=curRec.next(".r")}}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){var curRec=el.prev(".r");if(curRec.attr("data-record-type")=="215"||curRec.attr("data-record-type")=="706"){curRec=curRec.prev(".r")}}
if(curRec.length!=0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=curRec.attr("data-record-type");if(wrapper.length==0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");if(curRecType!="554"&&curRecType!="125"){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
if(curRecType=="734"||curRecType=="675"||curRecType=="279"||curRecType=="694"){curShapeEl.css("z-index","1")}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){var nearestBlock=el.next(".r")}else{var nearestBlock=el.prev(".r")}
if(nearestBlock.length==0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}